name: Release

env:
  TZ: Asia/Shanghai

permissions: write-all

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        
      - name: Run integration script
        run: ./main.bat
        
      - name: Upload generated files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: module
          path: Another-Plangothic-magisk-module.zip
      
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        
      - uses: actions/download-artifact@v3.0.2
        with:
          name: module
      
      #- name: Unzip the artifact
      #  run: |
      #    mkdir temp
      #    unzip Another-Plangothic-magisk-module.zip -d temp 
      
      - name: Release Action
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            Another-Plangothic-magisk-module.zip
          body_path: changelog.md
          #discussion_category_name: "公告"
